name       : qbittorrent
version    : 3.3.6
release    : 11
source     :
    - http://vorboss.dl.sourceforge.net/project/qbittorrent/qbittorrent/qbittorrent-3.3.6/qbittorrent-3.3.6.tar.xz : 5a1610311edd86023a6475dac20e24e89515d08a289d8bf0bf2ad1e27d4c624c
license    : GPL-2.0
component  : network.download
summary    : qBittorrent project aims to provide a Free Software alternative to µTorrent
description: |
    qBittorrent project aims to provide a Free Software alternative to µTorrent
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libtorrent-rasterbar)
    - pkgconfig(python-3.5)
    - pkgconfig(Qt5Core)
    - pkgconfig(QJson)
    - libboost-devel
setup      : |
    %configure --disable-static --with-qt5
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=%installroot%
