name       : qbittorrent
version    : 3.3.2
release    : 5
source     :
    - http://jaist.dl.sourceforge.net/project/qbittorrent/qbittorrent/qbittorrent-3.3.2/qbittorrent-3.3.2.tar.xz : e9330a63e0939fef79c70d5a66dba616f00206a70386efbb82fb7c620a19af58
license    : GPL-2.0
summary    : qBittorrent project aims to provide a Free Software alternative to µTorrent
description: |
    qBittorrent project aims to provide a Free Software alternative to µTorrent
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libtorrent-rasterbar)
    - pkgconfig(python-3.4)
    - pkgconfig(Qt5Core)
    - pkgconfig(QJson)
    - libboost-devel
setup      : |
    %configure --disable-static --with-qt5
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=%installroot%
