name       : qbittorrent
version    : 3.3.11
release    : 18
source     :
    - http://vorboss.dl.sourceforge.net/project/qbittorrent/qbittorrent/qbittorrent-3.3.11/qbittorrent-3.3.11.tar.xz : 4892ac5ed4bde2ed325fb67456698e703bb933b9eb1d146598259f4e2154a760
license    : GPL-2.0
component  : network.download
summary    : qBittorrent project aims to provide a Free Software alternative to µTorrent
description: |
    qBittorrent project aims to provide a Free Software alternative to µTorrent
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libtorrent-rasterbar)
    - pkgconfig(python-3.5)
    - pkgconfig(Qt5Help)
    - pkgconfig(QJson)
    - libboost-devel
setup      : |
    %configure --disable-static --with-qt5
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=%installroot%
