name       : qbittorrent
version    : 4.2.4
release    : 52
source     :
    - https://github.com/qbittorrent/qBittorrent/archive/release-4.2.4.tar.gz : caed269a80053f298a0c06a120223177b52baabba903f12fa725f102a2595061
homepage   : https://www.qbittorrent.org/
license    : GPL-2.0-or-later
component  : network.download
summary    : qBittorrent project aims to provide a Free Software alternative to µTorrent
description: |
    qBittorrent project aims to provide a Free Software alternative to µTorrent
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libtorrent-rasterbar)
    - pkgconfig(python3)
    - libboost-devel
rundeps    :
    - qt5-svg
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $workdir/dist/unix/menuicons/128x128/apps/qbittorrent.png $installdir/usr/share/pixmaps/qbittorrent.png
    install -Dm00644 $workdir/doc/qbittorrent.1 $installdir/usr/share/man/man1/qbittorrent.1
