name       : qbittorrent
version    : 4.5.5
release    : 81
source     :
    - https://github.com/qbittorrent/qBittorrent/archive/refs/tags/release-4.5.5.tar.gz : 73b01138f3681c0c7ef891a59a0fb038557c511dc16576752f772c244720d0c2
homepage   : https://www.qbittorrent.org/
license    : GPL-2.0-or-later
component  : network.download
summary    : qBittorrent project aims to provide a Free Software alternative to µTorrent
description: |
    qBittorrent project aims to provide a Free Software alternative to µTorrent
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libtorrent-rasterbar)
    - libboost-devel
rundeps    :
    - qt5-svg
setup      : |
    %cmake -DQT6=OFF
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $workdir/dist/unix/menuicons/128x128/apps/qbittorrent.png $installdir/usr/share/pixmaps/qbittorrent.png
    install -Dm00644 $workdir/doc/qbittorrent.1 $installdir/usr/share/man/man1/qbittorrent.1
