name       : qbittorrent
version    : 3.3.0
release    : 3
source     :
    - http://jaist.dl.sourceforge.net/project/qbittorrent/qbittorrent/qbittorrent-3.3.0/qbittorrent-3.3.0.tar.xz : ded08fcc1cf227700b81020395166541cd8c63efb2cbdfc97ac62be6458dbddb
license    : GPL-2.0
summary    : qBittorrent project aims to provide a Free Software alternative to µTorrent
description: |
    qBittorrent project aims to provide a Free Software alternative to µTorrent
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libtorrent-rasterbar)
    - pkgconfig(python-3.4)
    - pkgconfig(Qt5Core)
    - pkgconfig(QJson)
    - libboost-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=%installroot%
